changelog:
  exclude:
    labels:
      - skip-changelog
      - ignore-for-release
    authors:
      - dependabot
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: UI and UX
      labels:
        - ui
        - ux
        - design
    - title: Tooling and Maintenance
      labels:
        - dependencies
        - tooling
        - maintenance
        - chore
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"
